#! /bin/sh
### BEGIN INIT INFO
# Provides:          spark
# Required-Start:    $local_fs $all killprocs
# Required-Stop:
# Default-Start:     4
# Default-Stop:
# Short-Description: executed when entering runlevel 4 
### END INIT INFO

JAVA_HOME=/usr/lib/jvm/java-8-oracle
PATH=/sbin:/bin:$JAVA_HOME/bin

do_start () {
  su - spark --command "/home/spark/bin/start-spark-cluster.sh"
}

case "$1" in
  start)
  do_start
  ;;
  restart|reload|force-reload)
  echo "Error: argument '$1' not supported" >&2
  exit 3
  ;;
  stop|status)
  # No-op
  echo "Error: argument '$1' not supported yet" >&2
  ;;
  *)
  echo "Usage: $0 start|stop" >&2
  exit 3
  ;;
esac
